### PR TITLE
feat: implement command package

### PR DESCRIPTION
**Pull request by SkyderG**
- Implement Command package
- implement Player.sendMessage
- Implement TextNetworkHandler
- Remove old comments

### CODE REVIEW

**Comment by PMK744** [comment]
Merge in my latest commit, and also the launcher needs to have the new commands package in the package.json, add the package using "yarn add @serenityjs/command"

image

**Comment by SkyderG** [comment]
All done, anything else?

**Comment by SkyderG** [comment]
ok

**Comment by PMK744** [comment]
Looks good!

**Pull request merged**
